from __future__ import annotations

from typing import Any, Protocol


class BinaryViewLike(Protocol): ...


class DisassemblerAdapter(Protocol):
    def open_binary(self, path: str): ...

    def get_module_name(self, bv: BinaryViewLike) -> str: ...

    def get_file_version(self, bv: BinaryViewLike) -> str | None: ...

    def iter_functions(self, bv: BinaryViewLike): ...

    def function_name(self, fn: Any) -> str: ...

    def function_address(self, fn: Any) -> int: ...

    def function_callees_symbols(self, bv: BinaryViewLike, fn: Any) -> list[str]: ...

    def imported_modules(self, bv: BinaryViewLike) -> set[str]: ...

    def read_memory(self, bv: BinaryViewLike, address: int, size: int) -> bytes | None: ...

    def iter_instructions(self, fn: Any) -> Any: ...

    def get_call_parameter(self, bv: BinaryViewLike, fn: Any, call_addr: int, param_idx: int) -> int | None: ...
